apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:1.25-alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: app-conf
          mountPath: /etc/nginx
        - name: tls
          mountPath: /var/run/secrets/app/
          readOnly: true
      volumes:
      - name: app-conf
        configMap:
          name: app-conf
      - name: tls
        secret:
          secretName: app-tls
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - name: https
    protocol: TCP
    port: 443
