apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-istio-mtls-for-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: app
  mtls:
    mode: DISABLE
