apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tunnel-via-external-forward-proxy
spec:
  host: external-forward-proxy.corp.net
  trafficPolicy:
    tunneling:
      destinationPort: 8443
