global:
  configNamespace: istio-system
  useOpenshiftRouter: false       # Set to true if remote meshes use OpenShift router for ingress
  egressGateway:
    enabled: false
    service:
      name: istio-egressgateway
      namespace: istio-system
    port: 443
  # Remote meshes configuration - defines available remote meshes and their services
  remote: []
#  defaultServicePorts:
#  - number: 80
#    name: http
#    protocol: HTTP
#  local:
#    export:
#    - hostname: search.mesh.global
#      ports: [8000, 9000]
#  remote:
#  - mesh: east-mesh
#    addresses:
#    - 1.1.1.1
#    - 2.2.2.2
#    port: 15443
#    network: east-network
#    locality: us-east1
#    importedServices:
#    - foo.mesh.global
