apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-app
spec:
  hosts:
  - external-app.corp.net
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
