{{- if .Values.global.useOpenshiftRouter }}
{{- $local := get .Values.global "local" | default dict }}
{{- $exports := get $local "export" | default list }}
{{- range $export := $exports }}
{{- $ports := $export.ports | default $.Values.global.defaultServicePorts }}
{{- range $port := $ports }}
{{- $host := include "hostname.withPort" (dict "hostname" $export.hostname "port" $port.number) }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: export-{{ printf "%s" $export.hostname | replace "." "-" }}-{{ $port.number }}
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: federation-ingress-gateway
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      listener:
        name: "0.0.0.0_15443"
        filterChain:
          sni: "outbound_.{{ $port.number }}_._.{{ $export.hostname }}"
    patch:
      operation: MERGE
      value:
        filter_chain_match:
          server_names:
          - "{{ $host }}"
{{- end }}
{{- end }}
{{- end }}
