{{- $selector := .Values.global.gatewaySelector | default (dict "app" "federation-ingress-gateway") }}
{{- $port := .Values.global.port | default 15443 }}
{{- $exports := .Values.global.local.export | default list }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: federation-ingress-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- range $k, $v := $selector }}
    {{ $k }}: {{ $v }}
    {{- end }}
  servers:
  - port:
      number: {{ $port }}
      name: tls-passthrough
      protocol: TLS
    tls:
      mode: AUTO_PASSTHROUGH
    hosts:
    {{- range $svc := $exports }}
    - {{ $svc.hostname }}
    {{- end }}
