{{- if .Values.global.egressGateway.enabled }}
{{- $remotes := .Values.global.remote | default list }}
{{- if gt (len $remotes) 0 }}
{{- range $meshIdx, $mesh := $remotes }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ingress-{{ $mesh.mesh }}
  namespace: {{ $.Values.global.configNamespace }}
spec:
  exportTo:
  - "."
  hosts:
  - ingress.{{ $mesh.mesh }}.global
  ports:
  - number: {{ $mesh.port }}
    name: auto-passthrough-tls
    protocol: TLS
  {{/* TODO: resolution should depend on the address format - DNS for hostnames and STATIC for IP addresses */}}
  resolution: DNS
  location: MESH_INTERNAL
  endpoints:
  {{- range $addr := $mesh.addresses }}
  - address: {{ $addr }}
    ports:
      auto-passthrough-tls: {{ $mesh.port }}
    network: {{ $mesh.network }}
    {{- if $mesh.locality }}
    locality: {{ $mesh.locality }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
