apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: import-httpbin
spec:
  hosts:
  - httpbin.httpbin.svc.cluster.local
  ports:
  - number: 8000
    name: http
    protocol: HTTP
  endpoints:
  - address: {{.eastwestGatewayIP}}
    ports:
      http: 15443
    labels:
      app: httpbin
      security.istio.io/tlsMode: istio
  location: MESH_INTERNAL
  resolution: STATIC
