apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-address-pool
spec:
  addresses:
  - "{{.cidr}}"
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
