apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
spec:
  profile: minimal
  hub: quay.io/jewertow
  tag: custom-sds-for-root-ca
  components:
    pilot:
      k8s:
        env:
        - name: ROOT_CA_SDS_CLUSTER_NAME
          value: trust-bundle-sds
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    trustDomain: east.local
    trustDomainAliases:
    - west.local
  values:
    global:
      meshID: east-mesh
      multiCluster:
        clusterName: east
      network: east-network
