apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  version: v1.24.3
  namespace: istio-system
  updateStrategy:
    type: InPlace
  values:
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
    pilot:
      env:
        PILOT_ENABLE_IP_AUTOALLOCATE: "true"
    global:
      meshID: central-mesh
      multiCluster:
        clusterName: central-cluster
      network: central-network
