apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh-federation
  namespace: openshift-gitops
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/jewertow/istio-playground
    path: mesh-federation-helm-charts/mesh-admin
    targetRevision: mesh-federation-helm-charts
    helm:
      valueFiles:
      - $adminValues/west/global.yaml
  - repoURL: https://github.com/jewertow/mesh-federation-argo-mesh-admin
    targetRevision: west-cluster
    ref: adminValues
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
