apiVersion: v1
kind: Service
metadata:
  name: external-forward-proxy
spec:
  selector:
    app: external-forward-proxy
  ports:
  - name: https-connect
    protocol: TCP
    port: 3128
    targetPort: 3128
