apiVersion: v1
kind: ConfigMap
metadata:
  name: external-forward-proxy-ssl-certificate
data:
  external-forward-proxy.external.svc.cluster.local.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICzzCCAbcCAQAwDQYJKoZIhvcNAQELBQAwHzEdMBsGA1UEAwwUY2Euc3ZjLmNs
    dXN0ZXIubG9jYWwwHhcNMjIwNTMxMjAyMzAxWhcNMjMwNTMxMjAyMzAxWjA8MTow
    OAYDVQQDDDFleHRlcm5hbC1mb3J3YXJkLXByb3h5LmV4dGVybmFsLnN2Yy5jbHVz
    dGVyLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA25brryxJ
    3jBTHN40Vx1prGrtW6uP5sGbqMQwps2E5rYILRTEUrjfWwSmA8FrJaP0Wm4eOXz3
    WNIIXbeb3bhfVIB/NZzzRcbxi6Sp9D1JXo4xp7xi0HLe1DfYMPPR65+QZtfqtcFg
    uoVVvcRlDzKh/nW63PrMiaoHYYwBk9wan5mHVOFmuESsEUasN0fFwZkKzg4Ek5w3
    qQlJuU5rXhtitYFXyztQWcUZIam8oZvoaMRXXLteb/WOzof+AY4oo4s2UWKxKjdY
    Nu7toJSjLWyZoAwb3oBPrfGwTTK40h5uPyc7tZ93e278Ulxf48HLTuxziDdgxuyP
    o5pnfBVxNJsq4QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQA+uGWW10evTRTbs9/j
    dxPGNxBVRNUIB87GrCrgR1BBBIu9cict+vWmPdpv5WW86BMZXLsy8d0OkR1EsEnr
    CsskInRxvmOIQ5qWcqihc0Ge1bGCns+V6wRH2pI8B2/x5JsbG6pRkU8lh4UH85xE
    6IHz4XY5WvOqcBVgJqSMGO1u5yOCUnJlcAwJEH4bPWV7kJ1f1cxLNyBA/LTTHLz5
    hmn+BR5iRUKvPpzm/CFyVnBU8+X01fbtAyxhbiSKDT7Fb8Wy3dLP3oSoD++6lZwy
    0SlKD5kPwetzMmDahEI4fpbInBhxEUxDqf2Lliwu807P5MlGM7d75WJIEtNORAnV
    prJj
    -----END CERTIFICATE-----
