apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: import-httpbin
  namespace: istio-system
spec:
  hosts:
  - httpbin.httpbin.svc.cluster.local
  ports:
  - number: 8000
    name: http
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: {{ $.Values.eastwestGatewayIP }}
    ports:
      http: 15443
    network: west-network
    locality: west
    labels:
      app: httpbin
      security.istio.io/tlsMode: istio
