apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  values:
    global:
      meshID: {{ $.Values.localCluster }}-mesh
      multiCluster:
        clusterName: {{ $.Values.localCluster }}
      network: {{ $.Values.localCluster }}-network
      {{- if $.Values.debug }}
      logging:
        level: "all:debug"
      {{- end }}
  components:
    {{- if $.Values.eastwestIngressEnabled }}
    ingressGateways:
    - name: istio-eastwestgateway
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: {{ $.Values.localCluster }}-network
      enabled: true
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: {{ $.Values.localCluster }}-network
        service:
          ports:
          - name: tls
            port: 15443
            targetPort: 15443
    {{- end }}
    {{- if $.Values.eastwestEgressEnabled }}
    egressGateways:
    - name: istio-eastwestgateway-egress
      label:
        istio: eastwestgateway-egress
        app: istio-eastwestgateway-egress
        topology.istio.io/network: {{ $.Values.localCluster }}-network
      enabled: true
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: {{ $.Values.remoteCluster }}-network
        service:
          ports:
          - name: tls
            port: 15443
            targetPort: 15443
    {{- end }}
