apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns1-federation
  namespace: openshift-gitops
spec:
  destination:
    namespace: ns1
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/jewertow/istio-playground
    path: mesh-federation-helm-charts/namespace-admin
    targetRevision: mesh-federation-helm-charts
    helm:
      valueFiles:
      - $adminValues/east/global.yaml
      - $userValues/east/values.yaml
  - repoURL: https://github.com/jewertow/mesh-federation-argo-mesh-admin
    targetRevision: east-cluster
    ref: adminValues
  - repoURL: https://github.com/jewertow/mesh-federation-argo-namespace-admin
    targetRevision: east-cluster
    ref: userValues
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
