apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    kiali:
      enabled: false
    prometheus:
      enabled: true
    grafana:
      enabled: true
  gateways:
    egress:
      enabled: false
    openshiftRoute:
      enabled: false
  general:
    logging:
      componentLevels:
        default: info
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  tracing:
    type: None
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - bookinfo
