apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    kiali:
      enabled: false
    prometheus:
      enabled: true
    grafana:
      enabled: true
  gateways:
    egress:
      enabled: false
  general:
    logging:
      componentLevels:
        default: info
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  runtime:
    components:
      pilot:
        container:
          resources:
            requests:
              cpu: 250m
              memory: 1024Mi
        deployment:
          replicas: 2
  tracing:
    type: None
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    kiali:
      enabled: false
    prometheus:
      enabled: true
    grafana:
      enabled: true
  gateways:
    egress:
      enabled: false
  general:
    logging:
      componentLevels:
        default: info
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  runtime:
    components:
      pilot:
        container:
          resources:
            requests:
              cpu: 250m
              memory: 1024Mi
        deployment:
          replicas: 2
  tracing:
    type: None
  version: v2.4
